# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('proper', models.BooleanField()),
            ],
        ),
    ]
