# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aguas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='spot',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='place',
            name='place',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='place',
            name='proper',
            field=models.CharField(default='', max_length=255),
        ),
    ]
